import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Sidebar from "@/components/sidebar";
import ThemeProvider from "@/components/providers/theme-provider";
import ThemeToggle from "@/components/theme-toggle";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider> */}
        <Sidebar />
        <main className="sm:pl-64 mx-10">
          <div className="flex justify-end py-6">
            <ThemeToggle />
          </div>
          {children}
        </main>
        <Toaster />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
